Checker:
  severity: warning
  SuppressionFilter:
    file: config/checkstyle/suppressions.xml
    optional: true
  TreeWalker:
    ImportOrder:
      option: top
      groups: java,javax,org,com
      ordered: true
      separated: true
      sortStaticImportsAlphabetically: true
    UnusedImports: {}
    OuterTypeFilename: {}
    OneTopLevelClass: {}
    VisibilityModifier: {}
    WhitespaceAfter: {}
    WhitespaceAround: {}
    NoLineWrap: {}
    NeedBraces: {}
    LeftCurly: {}
    RightCurly: {}
    MethodParamPad: {}
    ParenPad: {}
    EmptyCatchBlock:
      exceptionVariableName: ignored|expected
    EqualsHashCode: {}
    MethodName: {}
    MemberName: {}
    LocalVariableName: {}
    ParameterName: {}
    TypeName: {}
    JavadocType: {}
    JavadocMethod:
      scope: public
      allowMissingParamTags: true
      allowMissingThrowsTags: true
      allowMissingReturnTag: true
      minLineCount: 2
    FinalClass: {}
    HideUtilityClassConstructor: {}
    AnnotationLocation: {}
    MissingOverride: {}
    LineLength:
      max: 110
      ignorePattern: "^package|^import|http(s)?://"
